### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Ciantic** [jariz/rivulet#1]
Hello, 

I'm interested in this file: https://github.com/jariz/rivulet/blob/master/packages/rivulet-server/typings/index.d.ts#L34-L159

Specifically `castv2-client` definitions. 

Castv2 is awful to use without typescript definitions, thanks for starting type definitions for it! I assume it's licensed under MIT because the package.json has line "MIT", but this repository does not have a LICENSE file or similar? Maybe you could add a LICENSE file here.

**Edit**: What a minefield. I found someone has typed whole chromecast-caf-reciever here: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/chromecast-caf-receiver which isn't tied to any NPM package but to the API.

As a side note: This Rivulet is interesting project, though I can't understand what it does (or was meant to do). But it has all the same dependencies as my project is supposed to have (mine is web based GUI for Chromecast that streams files from a server) the dependencies we share are node-ssdp, srt-to-vvt, castv2-client. Mine is not released yet, not sure will it ever be, these side projects tend to linger unfinished.

**Comment by jariz** [comment]
Hi, this is a dead project haha.
It was supposed to be a sort of plex-like site backed by [radarr](https://radarr.video/)/[sonarr](https://sonarr.tv/) that you could stream your media through.
Sort of like [streama](https://github.com/streamaserver/streama) but with way better streaming support (transcoding to a browser compatible format, DASH, etc)
Then I found out about [emby](https://emby.media/) and kind of lost interest in this project.

Eitherway, the typings are all there for you to use, glad at least some of the code is useful to someone else, I made a LICENSE file for you.
